services:
  ros:
    build: .
    container_name: reassemble
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - /dev:/dev
    tty: True
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # --- Addresses ---
      - ROBOT_IP=172.16.3.2
      - ROBOT_TYPE=fr3
      # - ARM_ID=fr3
      # - ROBOT_SERVER_IP=
      # - GPU_IP= 
    network_mode: host
    privileged: true
    devices:
      - /dev/hidraw0
      - /dev/hidraw1
      - /dev/hidraw2
      - /dev/hidraw3
      - "/dev/bus/usb:/dev/bus/usb"
    command: /bin/bash
