services:
  ros:
    build:
      context: ./..
      dockerfile: .docker/Dockerfile
    container_name: reassemble
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: True
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROBOT_IP=${ROBOT_IP}
      - ROBOT_TYPE=${ROBOT_TYPE}
      - NATNET_IP=${NATNET_IP}
      - ROBOT_SERVER_IP=${ROBOT_SERVER_IP}
    network_mode: host
    privileged: true
    devices:
      - /dev/hidraw0
      - /dev/hidraw1
      - /dev/hidraw2
      - /dev/hidraw3
      - "/dev/bus/usb:/dev/bus/usb"
    command: /bin/bash
